version: '2'

services:
   restheart:
      image: softinstigate/restheart:3.1.1
      container_name: restheart
      depends_on:
            - mongodb
      ports:
            - "8080:8080"
      
   mongodb:
      image: mongo:3.4.4
      container_name: mongo
      ports:
            - "27017:27017"
      